# Generated by Django 5.0.3 on 2024-03-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostData_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_month', models.IntegerField()),
                ('p_group', models.CharField(max_length=100)),
                ('p_area', models.CharField(max_length=100)),
                ('p_company', models.CharField(max_length=100)),
                ('p_department', models.CharField(max_length=100)),
                ('p_function', models.CharField(max_length=100)),
                ('p_state', models.CharField(max_length=100)),
                ('p_classification', models.CharField(max_length=100)),
                ('p_position_function', models.CharField(max_length=100)),
                ('cost_sb_simple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_gjj_simple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_salary_simple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_sb_multiple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_gjj_multiple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_salary_multiple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_sbgjj_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_salary_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_costs.costdata_year')),
            ],
        ),
        migrations.AddField(
            model_name='costdata_year',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_costs.employee'),
        ),
    ]
